apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tailscale-secrets-provider
spec:
  provider: aws
  secretObjects:
    - secretName: tailscale-subnet-router-secrets
      type: Opaque
      data:
        - objectName: "tailscale_auth_key"
          key: AUTH_KEY
        
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:eu-west-3:883152518512:secret:coverflex_tailscale_subnet_router-WIjgXh
        jmesPath:
            - path: "tailscale_auth_key"
              objectAlias: "tailscale_auth_key"
