name: Tailscale subnet router

on: push
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup helm tool
        uses: azure/setup-helm@v3

      - name: Run Helm lint against chart
        run: helm lint charts/tailscale-subnet-router

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::883152518512:role/tailscale-subnet-router-GithubActions
          aws-region: eu-west-3

      - name: Get secrets by name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            arn:aws:secretsmanager:eu-west-3:883152518512:secret:coverflex_tailscale_githubactions-9VIndJ
          parse-json-secrets: true
      
      - name: deploy tailscale
        run: |
          aws eks update-kubeconfig --name coverflex-staging-20221130
          helm upgrade --install tailscale-subnet-router ./charts/tailscale-subnet-router -f values.yml -n tailscale --wait --timeout 5m

      # - name: Get tailscale API key
      #   run: |
      #     TAILSCALE_API_KEY=$(curl -d "client_id=${COVERFLEX_GITHUB_ACTIONS_OAUTH_CLIENT_ID}" \
      #       -d "client_secret=${COVERFLEX_GITHUB_ACTIONS_OAUTH_CLIENT_SECRET}" \
      #       "https://api.tailscale.com/api/v2/oauth/token" | jq -j .access_token)
      #     echo "TAILSCALE_API_KEY=${TAILSCALE_API_KEY}" >> $GITHUB_ENV

      # - name: Deploy ACL
      #   if: github.event_name == 'push'
      #   id: deploy-acl
      #   uses: tailscale/gitops-acl-action@v1
      #   with:
      #     api-key: ${{ env.TAILSCALE_API_KEY }}
      #     tailnet: ${{ env.COVERFLEX_GITHUB_ACTIONS_TAILSCALE_TAILNET }}
      #     action: apply

      # - name: Test ACL
      #   if: github.event_name == 'pull_request'
      #   id: test-acl
      #   uses: tailscale/gitops-acl-action@v1
      #   with:
      #     api-key: ${{ env.TAILSCALE_API_KEY }}
      #     tailnet: ${{ env.COVERFLEX_GITHUB_ACTIONS_TAILSCALE_TAILNET }}
      #     action: test